version: '3.8'

services:
  e2e-postgres:
    container_name: db-main-e2e-postgresql
    image: postgres:14-alpine
    ports:
      - target: 5432
        published: 5432
        protocol: tcp
    environment:
      - POSTGRES_DB=e2edb
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready']
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - e2e_db_data:/var/lib/postgresql/data:rw

  postgres_is_ready:
    image: postgres
    depends_on:
      postgres:
        condition: service_healthy

volumes:
  e2e_db_data:
