export const filteredRepos = [
  ['nextjs-monorepo-example', ['typescript', 'react']],
  ['cache-interop', ['typescript', 'node']],
  ['httpx', ['typescript', 'node', 'npm']],
  ['nextvalid', ['typescript', 'nextjs', 'node']],
  ['soluble-japha', ['php7.1']],
  ['soluble-mediatools', ['php7.1', 'ffmpeg']],
  ['perso', ['typescript', 'react']],
  //  ['bluewind', ['typescript', 'express', 'react', 'lerna']],
  // ['dbal', ['doctrine', 'contributor']],
  ['soluble-jasper', ['php7.1', 'reports', 'pdf']],
  // ['desync', ['typescript', 'react', 'lerna']],
  // ['soluble-metadata', ['php7.1', 'db']],
  ['php-java-bridge', ['java', 'fork!']],
  ['mfts', ['typescript', 'react', 'pwa', 'spare-time']],
] as const;
