name: CI-e2e-db-main

on:
  push:
    branches:
      - dev
      - main
    paths:
      - 'packages/db-main'
      - '.github/workflows/**'

  pull_request:
    types:
      - opened
      - synchronize
      - reopened
    paths:
      - 'packages/db-main'
      - '.github/workflows/**'

jobs:
  e2e:
    # containers must run in Linux based operating systems
    runs-on: ubuntu-latest
    timeout-minutes: 10

    strategy:
      fail-fast: false
      matrix:
        node-version: [16.X]

    steps:
      - uses: actions/checkout@v3

      - uses: pnpm/action-setup@v2.2.2
        with:
          version: 7

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'pnpm'

      - name: Start postgresql
        working-directory: packages/db-main
        run: docker-compose -f docker-compose.e2e.yml up --detach

      - name: Install dependencies
        run: |
          pnpm install
        env:
          PRISMA_SKIP_POSTINSTALL_GENERATE: true
          PLAYWRIGHT_SKIP_BROWSER_DOWNLOAD: 1
          HUSKY: 0

      - name: E2E prisma
        working-directory: packages/db-main
        run: |
          pnpm run test-e2e
        env:
          E2E_PRISMA_DATABASE_URL: postgresql://postgres:postgres@localhost:5432/db-main-e2e?schema=public
