name: CI-e2e-db-main

on:
  push:
    branches:
      - dev
      - main
    paths:
      - 'packages/db-main'
      - '.github/workflows/**'

  pull_request:
    types:
      - opened
      - synchronize
      - reopened
    paths:
      - 'packages/db-main'
      - '.github/workflows/**'

jobs:
  e2e:
    # containers must run in Linux based operating systems
    runs-on: ubuntu-latest
    timeout-minutes: 10

    strategy:
      fail-fast: false
      matrix:
        node-version: [16.X]

    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: 📥 Monorepo install
        uses: ./.github/actions/yarn-nm-install

      - name: Start postgresql
        working-directory: packages/db-main
        run: docker-compose -f docker-compose.e2e.yml up --detach

      - name: E2E prisma
        working-directory: packages/db-main
        run: |
          yarn test-e2e
        env:
          E2E_PRISMA_DATABASE_URL: postgresql://postgres:postgres@localhost:5432/db-main-e2e?schema=public
