name: CI-e2e-website

on:
  push:
    branches:
      - dev
      - main
    paths:
      - 'apps/website/**'
      - 'packages/**'
      - 'package.json'
      - '*.lock'
      - '.yarnrc.yml'
      - '*.base.json'
      - '*.base.js'
      - '.prettier*.*'
      - '.github/workflows/**'

  pull_request:
    types: [opened, synchronize, reopened]
    # Optional:
    #   Only consider those files/paths to trigger the github action
    #   to prevent unnecessary builds.
    paths:
      - 'apps/website/**'
      - 'packages/**'
      - 'package.json'
      - '*.lock'
      - '.yarnrc.yml'
      - '*.base.json'
      - '*.base.js'
      - '.prettier*.*'
      - '.github/workflows/**'

jobs:
  e2e:
    timeout-minutes: 10

    strategy:
      fail-fast: false
      matrix:
        node-version: [16.x]
        os: [ubuntu-latest]

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: 📥 Monorepo install
        uses: ./.github/actions/yarn-nm-install

      # see https://github.com/vercel/next.js/pull/27362
      - name: Restore nextjs build website from cache
        uses: actions/cache@v3
        with:
          path: |
            ${{ github.workspace }}/apps/website/.next/cache
            ${{ github.workspace }}/.cache
            ${{ github.workspace }}/**/tsconfig.tsbuildinfo

          key: ${{ runner.os }}-website-${{ hashFiles('**/yarn.lock') }}-${{ hashFiles('apps/website/src/**.[jt]sx?', 'apps/website/src/**.json') }}
          restore-keys: |
            ${{ runner.os }}-website-${{ hashFiles('**/yarn.lock') }}-

      - name: Start database
        working-directory: packages/db-main
        run: docker-compose -f docker-compose.e2e.yml up --detach

      - name: Create and seed test database
        working-directory: packages/db-main
        run: |
          yarn prisma db push
          yarn prisma db seed
        env:
          PRISMA_DATABASE_URL: postgresql://postgres:postgres@localhost:5432/webapp-e2e?schema=public

      - name: Build website
        working-directory: apps/website
        run: |
          yarn build
        env:
          PRISMA_DATABASE_URL: postgresql://postgres:postgres@localhost:5432/webapp-e2e?schema=public
          # Don't need to lint / typecheck for e2e, they're done in another workflow
          NEXTJS_IGNORE_ESLINT: true
          NEXTJS_IGNORE_TYPECHECK: true
          NEXT_DISABLE_SOURCEMAPS: true
          NEXT_TELEMETRY_DISABLED: true
          NEXTJS_SENTRY_UPLOAD_DRY_RUN: true
          NEXT_PUBLIC_PUSHER_CLUSTER: eu
          NEXT_PUBLIC_PUSHER_KEY: blah
          PUSHER_APP_ID: 111
          PUSHER_SECRET: balah

      - name: 📥 Playwright install
        uses: ./.github/actions/playwright-install

      - name: E2E run website playwright tests
        working-directory: apps/website
        run: |
          xvfb-run --auto-servernum --server-args="-screen 0 1280x960x24" -- yarn test-e2e
        env:
          E2E_WEBSERVER_MODE: START
          CI: 1
          PRISMA_DATABASE_URL: postgresql://postgres:postgres@localhost:5432/webapp-e2e?schema=public

      - uses: actions/upload-artifact@v3
        if: always()
        with:
          name: website-playwright-test-results
          path: apps/website/e2e/.out
