name: CI-e2e-website

on:
  push:
    branches:
      - dev
      - main
    paths:
      - 'apps/website/**'
      - 'packages/**'
      - 'package.json'
      - 'yarn.lock'
      - '.yarnrc.yml'
      - '*.base.json'
      - '*.base.js'
      - '.prettier*.*'
      - '.github/workflows/**'

  pull_request:
    types:
      - opened
      - synchronize
      - reopened
    # Optional:
    #   Only consider those files/paths to trigger the github action
    #   to prevent unnecessary builds.
    paths:
      - 'apps/website/**'
      - 'packages/**'
      - 'package.json'
      - 'yarn.lock'
      - '.yarnrc.yml'
      - '*.base.json'
      - '*.base.js'
      - '.prettier*.*'
      - '.github/workflows/**'

jobs:
  e2e:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    strategy:
      fail-fast: false
      matrix:
        node-version: [16.X]
        database:
          - e2e-postgres

    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      # Why not using setup-node 2.2+ cache option (yet) ?
      # see https://github.com/belgattitude/nextjs-monorepo-example/pull/369
      - name: Get yarn cache directory path
        id: yarn-cache-dir-path
        run: echo "::set-output name=dir::$(yarn config get cacheFolder)"

      - name: Restore yarn cache
        uses: actions/cache@v3
        id: yarn-cache # use this to check for `cache-hit` (`steps.yarn-cache.outputs.cache-hit != 'true'`)
        with:
          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: yarn-cache-folder-${{ hashFiles('**/yarn.lock', '.yarnrc.yml') }}
          restore-keys: |
            yarn-cache-folder-

      # see https://github.com/vercel/next.js/pull/27362
      - name: Restore nextjs build website from cache
        uses: actions/cache@v3
        with:
          path: |
            ${{ github.workspace }}/apps/website/.next/cache
            ${{ github.workspace }}/.cache
            ${{ github.workspace }}/**/tsconfig.tsbuildinfo
            ${{ github.workspace }}/**/.eslintcache

          key: ${{ runner.os }}-website-${{ hashFiles('**/yarn.lock') }}-${{ hashFiles('apps/website/src/**.[jt]sx?', 'apps/website/src/**.json') }}
          restore-keys: |
            ${{ runner.os }}-website-${{ hashFiles('**/yarn.lock') }}-

      - name: Start database
        working-directory: packages/db-main
        run: docker-compose -f docker-compose.e2e.yml up --detach ${{ matrix.database }}

      - name: Install dependencies
        run: |
          yarn install --immutable
        env:
          PLAYWRIGHT_SKIP_BROWSER_DOWNLOAD: 1

      - name: Create and seed test database
        working-directory: packages/db-main
        run: |
          yarn prisma db push
          yarn prisma db seed
        env:
          PRISMA_DATABASE_URL: postgresql://postgres:postgres@localhost:5432/webapp-e2e?schema=public

      - name: Build website
        working-directory: apps/website
        run: |
          yarn build
        env:
          PRISMA_DATABASE_URL: postgresql://postgres:postgres@localhost:5432/webapp-e2e?schema=public
          # Don't need to lint / typecheck for e2e, they're done in another workflow
          NEXTJS_IGNORE_ESLINT: true
          NEXTJS_IGNORE_TYPECHECK: true
          NEXT_DISABLE_SOURCEMAPS: true
          NEXT_TELEMETRY_DISABLED: true
          NEXTJS_SENTRY_UPLOAD_DRY_RUN: true
          NEXT_PUBLIC_PUSHER_CLUSTER: eu
          NEXT_PUBLIC_PUSHER_KEY: blah
          PUSHER_APP_ID: 111
          PUSHER_SECRET: balah

      # Playwright recommends if you cache the binaries to keep it tied to the version of playwright you are using.
      # https://playwright.dev/docs/ci#caching-browsers
      - name: Get current Playwright version
        id: playwright-version
        run: |
          playwright_version=$(npm --json list @playwright/test | jq -r .dependencies[].version)
          echo "::set-output name=version::${playwright_version}"

      - name: Cache Playwright binaries
        uses: actions/cache@v3
        id: playwright-cache
        with:
          path: |
            ~/.cache/ms-playwright
          key: cache-playwright-${{ steps.playwright-version.outputs.version }}

      - name: Install Playwright
        if: steps.playwright-cache.outputs.cache-hit != 'true'
        run: npx playwright install --with-deps chromium webkit

      - name: E2E run website playwright tests
        working-directory: apps/website
        run: |
          xvfb-run --auto-servernum --server-args="-screen 0 1280x960x24" -- yarn test-e2e
        env:
          E2E_WEBSERVER_MODE: START
          CI: 1
          PRISMA_DATABASE_URL: postgresql://postgres:postgres@localhost:5432/webapp-e2e?schema=public

      - uses: actions/upload-artifact@v3
        if: always()
        with:
          name: website-playwright-test-results
          path: apps/website/e2e/.out
