name: CI-packages

on:
  push:
    branches:
      - dev
      - main
    paths:
      - 'packages/**'
      - 'yarn.lock'
      - '.yarnrc.yml'
      - '.prettier*.*'
      - '*.base.json'
      - '*.base.js'
      - '.prettier*.*'
      - '.github/workflows/**'

  pull_request:
    types:
      - opened
      - synchronize
      - reopened
    paths:
      - 'packages/**'
      - 'yarn.lock'
      - '.yarnrc.yml'
      - '*.base.json'
      - '*.base.js'
      - '.prettier*.*'
      - '.github/workflows/**'

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x]
    steps:
      - uses: actions/checkout@v3
        with:
          # Fetch all git history so that yarn workspaces --since can compare with the correct commits
          # @link https://github.com/actions/checkout#fetch-all-history-for-all-tags-and-branches
          fetch-depth: 0

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: 📥 Monorepo install
        uses: ./.github/actions/yarn-nm-install

      - name: Restore packages cache
        uses: actions/cache@v3
        with:
          path: |
            ${{ github.workspace }}/.cache
            ${{ github.workspace }}/**/tsconfig.tsbuildinfo

          key: ${{ runner.os }}-packages-cache-${{ hashFiles('**/yarn.lock') }}-${{ hashFiles('packages/**.[jt]sx?', 'packages/**.json') }}
          restore-keys: |
            ${{ runner.os }}-packages-cache-${{ hashFiles('**/yarn.lock') }}-

      - name: Typecheck
        run: |
          yarn g:nx run-many --target=typecheck --all --exclude=website

      - name: Prettier checks
        run: |
          yarn g:nx run-many --target=prettier-check --all --exclude=website

      - name: Eslint checks
        run: |
          yarn g:nx run-many --target=lint --all --exclude=website        

      - name: Stylelint checks
        run: |
          yarn g:nx run-many --target=lint-styles --all --exclude=website

      - name: Unit tests changed packages
        run: |
          yarn g:nx run-many --target=test-unit --all --exclude=website

      - name: Run build for changed packages
        run: |
          yarn g:nx run-many --target=build --all --exclude=website

      - name: Check build for size-limits
        run: |
          yarn g:nx run-many --target=check-size --all --exclude=website

      - name: Check build ecmascript compliance
        run: |
          yarn g:nx run-many --target=check-dist --all --exclude=website

      - name: Run storybook build for changed packages
        run: |
          yarn g:nx run-many --target=build-storybook --all --exclude=website
