name: ReleaseOrVersionPR

on:
  push:
    branches:
      - main

jobs:
  release:
    # Ensure this workflow is never run outside this repo and limit release to main branch (not from a remote branch)
    if: ${{ github.repository == 'belgattitude/perso' && contains('refs/heads/main',github.ref)}}
    name: Release and changelog
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3
        with:
          # To run comparison we need more than the latest commit. Keep the fetch-depth relatively
          # high or set it to zero to get all commits from the git repo.
          # @link https://github.com/actions/checkout#fetch-all-history-for-all-tags-and-branches
          fetch-depth: 0

      - name: Use Node.js 16.x
        uses: actions/setup-node@v3
        with:
          node-version: 16.x

      - name: 📥 Monorepo install
        uses: ./.github/actions/yarn-nm-install

      # @link https://github.com/changesets/action
      - name: Create Release Pull Request
        id: changesets
        uses: changesets/action@v1
        env:
          # See https://github.com/changesets/action/issues/147
          HOME: ${{ github.workspace }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
