name: ReleaseOrVersionPR

on:
  push:
    branches:
      - main

jobs:
  release:
    if: github.repository == 'belgattitude/perso'
    name: Release and changelog
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@master
        with:
          # To run comparison we need more than the latest commit. Keep the fetch-depth relatively
          # high or set it to zero to get all commits from the git repo.
          # @link https://github.com/actions/checkout#fetch-all-history-for-all-tags-and-branches
          fetch-depth: 25

      - name: Use Node.js 16.x
        uses: actions/setup-node@v3
        with:
          node-version: 16.x

      - uses: pnpm/action-setup@v2.2.2
        with:
          version: 7

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install
        env:
          PRISMA_SKIP_POSTINSTALL_GENERATE: true
          PLAYWRIGHT_SKIP_BROWSER_DOWNLOAD: 1
          HUSKY: 0


      # @link https://github.com/changesets/action
      - name: Create Release Pull Request
        id: changesets
        uses: changesets/action@v1
        env:
          # See https://github.com/changesets/action/issues/147
          HOME: ${{ github.workspace }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
